# Generated by Django 4.0.4 on 2022-05-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_qualifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='assignees',
            field=models.ManyToManyField(blank=True, through='api.MeetingTaskPerson', to='api.person'),
        ),
        migrations.AlterField(
            model_name='meetingtaskperson',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meeting'),
        ),
        migrations.AlterField(
            model_name='task',
            name='qualifiers',
            field=models.ManyToManyField(blank=True, related_name='qualified_for', to='api.person'),
        ),
    ]
