# Generated by Django 4.0.4 on 2022-05-02 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_meeting_assignees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='task',
            new_name='tasks',
        ),
    ]
