# Generated by Django 4.0.4 on 2022-05-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_task_meeting_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingtaskperson',
            options={},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='api.MeetingTaskPerson', to='api.task'),
        ),
    ]
