# Generated by Django 4.0.4 on 2022-05-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_meetingtaskperson_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='tasker',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='api.MeetingTaskPerson', to='api.task'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='persons', through='api.MeetingTaskPerson', to='api.person'),
        ),
    ]
