# Generated by Django 4.0.4 on 2022-05-03 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_meeting_tasker_alter_meeting_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='assignees',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='tasker',
        ),
        migrations.AlterField(
            model_name='meetingtaskperson',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignees', to='api.meeting'),
        ),
    ]
