# Generated by Django 4.0.4 on 2022-05-03 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_meeting_description_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='tasks',
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('tasks', models.ManyToManyField(to='api.task')),
            ],
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.meetingtype'),
        ),
    ]
