# Generated by Django 4.0.4 on 2022-05-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_period_meetingtype_occurences_meetingtype_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blacklists',
            field=models.ManyToManyField(related_name='blacklisted_by', to='api.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='singleton',
            field=models.BooleanField(default=True),
        ),
    ]
